server:
  port: 8080
app:
  filter:
    default:
      page:
        size: 30
        number: 1
        maxSize: 50
spring:
  application:
    name: electronic-shop
  jpa:
    properties:
      hibernate:
        show_sql: true
        generate_statistics: true
        order_inserts: true
        jdbc.batch_size: 100
        generate-ddl: false
        ddl-auto: create
  datasource:
    url: jdbc:h2:mem:bank
    driverClassName: org.h2.Driver
    username: sa
    password: